language: go

go:
- 1.13.x

install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.61.0/hugo_0.61.0_Linux-64bit.deb
- sudo dpkg -i hugo_0.61.0_Linux-64bit.deb
- pip install --user awscli

script:
  - if [ $TRAVIS_BRANCH == "master" ]; then
      echo "building production";
      hugo;
    else
      echo "building staging";
      STAGING=true hugo;
    fi

deploy:
  # PROD DEPLOY ON CHANGES TO MASTER
  - provider: script
    script: chmod +x ./deploy.sh && ./deploy.sh master prod.embrace.io
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    local_dir: public
    upload-dir: prod
    on:
      branch: master
  # STAGING DEPLOY ON CHANGES TO BRANCHES EXCEPT MASTER
  - provider: script
    script: chmod +x ./deploy.sh && ./deploy.sh staging dev.embrace.io
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    local_dir: public
    upload-dir: stg
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != "master"

after_deploy:
  - if [ $TRAVIS_BRANCH == "master" ]; then
      echo "invalidating $TRAVIS_BRANCH cloudfront";
      aws cloudfront create-invalidation --distribution-id $PROD_CLOUDFRONT_DISTRIBUTION_ID --paths "/*";
    else
      echo "invalidating $TRAVIS_BRANCH cloudfront";
      aws cloudfront create-invalidation --distribution-id $STG_CLOUDFRONT_DISTRIBUTION_ID --paths "/*";
    fi

