language: go

go:
- 1.13.x

env:
  global:
    HUGO_VERSION: '0.73.0'

_hugo-build-deploy: &hugo-build-deploy
  stage: deploy
  install:
    - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_{$HUGO_VERSION}_Linux-64bit.deb
    - sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
    - pip install --user awscli
  script:
    - echo "Building ${ENV}"
    - hugo
    - echo "Deploying ${ENV} into ${BUCKET}"
    - aws s3 sync --acl public-read --delete public/ s3://${BUCKET}
    - echo "Invalidating ${BUCKET} cloudfront cache"
    - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths "/*";

jobs:
  include:
    - <<: *hugo-build-deploy
      name: deploy to staging
      if: (branch = setup-travis) AND (NOT type IN (pull_request))
      env:
        - ENV=stg
        - STAGING=true
        - BUCKET="dev.embrace.io-docs"
        - CLOUDFRONT_ID="E20WGO1Z361L37"
    - <<: *hugo-build-deploy
      name: deploy to production
      if: tag =~ ^([0-9]+\.[0-9]+\.[0-9]+)$ AND (branch = master)
      env:
        - ENV=prod
        - BUCKET=prod.embrace.io-docs
        - CLOUDFRONT_ID="ENILO2YUDEJ88"

