baseURL: "https://embrace.io/docs/"
languageCode: "en-us"
title: "Embrace Docs"
theme: "book"
publishDir: "public/docs"
outputs:
  page:
    - AMP
    - HTML
  home:
    - HTML
    - AMP
  section:
    - HTML
    - AMP

params:
  sdkVersion:
    ios: "4.2.0"
    android: "4.4.0"
    rn: "3.4.0"
  BookSection: '*'
  BookMenuReset: false

markup:
  goldmark:
    renderer:
      unsafe: true
