baseURL: "https://embrace.io/docs/"
disableHugoGeneratorInject: true
languageCode: "en-us"
title: "Embrace Docs"
theme: "book"
publishDir: "public/docs"
outputs:
  page:
  - AMP
  - HTML
  home:
  - HTML
  - AMP
  section:
  - HTML
  - AMP
params:
  sdkVersion:
    ios: "5.7.5"
    android: "5.0.1"
    rn: "3.9.1"
    unity: "1.4.0"
    unity_android: "4.11.3"
  BookSection: '*'
  BookMenuReset: false
markup:
  goldmark:
    renderer:
      unsafe: true
