baseURL: "https://embrace.io/docs/"
disableHugoGeneratorInject: true
languageCode: "en-us"
title: "Embrace Docs"
theme: "hugo-book"
publishDir: "public/docs"
outputs:
  page:
    - AMP
    - HTML
  home:
    - HTML
    - AMP
  section:
    - HTML
    - AMP
params:
  sdkVersion:
    ios: "5.16.3"
    android: "5.14.2"
    rn: "3.10.0"
    rn_screen_tracker: "0.0.1"
    unity: "1.10.1"
    unity_android: "5.13.0"
  BookSection: '*'
  BookMenuReset: false
  BookTheme: light
markup:
  goldmark:
    renderer:
      unsafe: true
