baseURL: "https://embrace.io/docs/"
languageCode: "en-us"
title: "Embrace Docs"
theme: "book"
publishDir: "public/docs"
outputs:
  page:
    - AMP
    - HTML
  home:
    - HTML
    - AMP
  section:
    - HTML
    - AMP

params:
  sdkVersion:
    ios: "5.5.0"
    android: "4.8.3"
    rn: "3.7.1"
    unity: "1.2.2"
  BookSection: '*'
  BookMenuReset: false

markup:
  goldmark:
    renderer:
      unsafe: true
