baseURL: "http://example.org/docs/"
languageCode: "en-us"
title: "Embrace Docs"
theme: "book"
publishDir: "public/docs"
outputs:
  page:
    - AMP
    - HTML
  home:
    - HTML
    - AMP
  section:
    - HTML
    - AMP

params:
  sdkVersion:
    ios: "4.1.18"
    android: "4.2.5"
    rn: "2.0.0"
  BookSection: '*'
  BookMenuReset: false
  BookLogo: 'images/embrace-logo.png'
  BookLogoWidth: 200
  BookLogoHeight: 60
  BookRepo: 'https://github.com/embrace-io/embrace-docs'
  BookEditPath: 'edit/master/content/'

markup:
  goldmark:
    renderer:
      unsafe: true
