baseURL: "https://embrace.io/docs/"
disableHugoGeneratorInject: true
languageCode: "en-us"
title: "Embrace Docs"
theme: "book"
publishDir: "public/docs"

outputs:
  page:
    - AMP
    - HTML
  home:
    - HTML
    - AMP
  section:
    - HTML
    - AMP

params:
  sdkVersion:
    ios: "5.5.2"
    android: "4.9.2"
    rn: "3.8.0"
    unity: "1.2.10"
    unity_android: "4.9.2"
  BookSection: '*'
  BookMenuReset: false

markup:
  goldmark:
    renderer:
      unsafe: true
