baseURL: "https://embrace.io/docs/"
languageCode: "en-us"
title: "Embrace Docs"
theme: "book"
publishDir: "public/docs"
outputs:
  page:
    - AMP
    - HTML
  home:
    - HTML
    - AMP
  section:
    - HTML
    - AMP

params:
  sdkVersion:
    ios: "4.1.18"
    android: "4.2.9"
    rn: "3.4.0"
  BookSection: '*'
  BookMenuReset: false
  BookRepo: 'https://github.com/embrace-io/embrace-docs'
  BookEditPath: 'edit/master/content/'

markup:
  goldmark:
    renderer:
      unsafe: true
