name: Release Drafter

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate next version
        id: calver
        run: |
          export next_version=$(sh scripts/get_next_version_tag.sh)
          echo "version=${next_version}" >> $GITHUB_OUTPUT
          echo "Next version will be: ${next_version}" >> $GITHUB_STEP_SUMMARY
      - uses: embrace-io/release-drafter@v5
        with:
          disable-autolabeler: true
          name: ${{ steps.calver.outputs.version }}
          tag: ${{ steps.calver.outputs.version }}
          version: ${{ steps.calver.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
