name: "Close Stale PRs"
on:
  schedule:
    - cron: "30 1 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          exempt-pr-labels: "dependencies"
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          stale-pr-message: "This PR is stale because it has been open 20 days with no activity. Remove stale label or comment or this PR will be closed in 10 days."
          close-pr-message: "This PR was closed because it has been stalled for 30 days with no activity."
          days-before-pr-stale: 20
          days-before-pr-close: 10
          operations-per-run: 100
